use_frameworks!

platform :ios, '9.0'

target 'BCHomeComponent_Example' do
  pod 'BCHomeComponent', :path => '../'
  
  pod 'CTMediator'
  pod 'SnapKit'
  target 'BCHomeComponent_Tests' do
    inherit! :search_paths

  end
end
